; LunaXP Studio starter preset - Teal
[Palette]
Window.ActiveCaption=#168A8A
Window.InactiveCaption=#5D7979
Window.ActiveFrame=#168A8A
Window.InactiveFrame=#5D7979
Taskbar.Background=#0E6666
StartMenu.StartButton=#168A8A
